server:
  port: 8083
  servlet:
    context-path: /system

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
    username: root
    password: 1234root
    hikari:
      maximum-pool-size: 5
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true